### ISSUE TITLE
<feature request>Depth map mask to specify blur location (Blur background only)

### ISSUE THREAD

**Issue by mimimi999** [KohakuBlueleaf/a1111-sd-webui-haku-img#10]
Hello. I'm leaving a comment as you seem to be accepting feature requests.
Is it possible to specify the blur location (blur only the background) with a depth map mask?

(create depth map from one image)
https://github.com/isl-org/MiDaS
https://huggingface.co/spaces/pytorch/MiDaS

If you can do this, the quality of the generated image for live action will be greatly improved
I'm a programming novice, so I'm not sure if it can actually be implemented, but I'd appreciate it if you could check it out.

**Comment by KohakuBlueleaf** [comment]
@mimimi999 I will add masked blur at first and see if there are any way to let user to upload masks

I think in this way you can use any kind of xxx map or xxx mask to specify which part you want to blur/ do other effect

**Comment by KohakuBlueleaf** [comment]
I think the layer feature with different blend mode (and mask) actually support masked blur
Since sd-webui itself is planning to update gradio from 3.xx to 4.xx
Upload your own mask will be a planned feature until that (4.xx have lot of breaking changes so I don't want to implement UI/UX related feature for now, you can open new issue for this if the gradio4 PR is merged)
